server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 1q2w3e4r12!
    key-store-type: PKCS12
    key-alias: spring
  tomcat:
    uri-encoding: UTF-8
  port: 443
